<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <IsPackable>false</IsPackable>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Akka.Persistence" Version="1.5.31" />
    <PackageReference Include="Akka.TestKit" Version="1.5.31" />
    <PackageReference Include="Akka.TestKit.Xunit2" Version="1.5.31" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="config.conf" />
  </ItemGroup>

</Project>
