akka {
  persistence {
    journal {
      plugin = "akka.persistence.journal.test"
      auto-start-journals = ["akka.persistence.journal.test"]

      test {
        class = "Akka.HealthCheck.Persistence.TestKit.Journal.TestJournal, Akka.HealthCheck.Persistence.TestKit"
        plugin-dispatcher = "akka.actor.default-dispatcher"
      }
    }

    snapshot-store {
      plugin = "akka.persistence.snapshot-store.test"
      auto-start-snapshot-stores = ["akka.persistence.snapshot-store.test"]

      test {
        class = "Akka.HealthCheck.Persistence.TestKit.SnapshotStore.TestSnapshotStore, Akka.HealthCheck.Persistence.TestKit"
        plugin-dispatcher = "akka.actor.default-dispatcher"        
      }
    }
  }
}