# Pull request validation for Windows against the `dev` and `master` branches
# See https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema for reference
trigger:
  branches:
    include:
      - dev
      - master

pr:
  autoCancel: true # indicates whether additional pushes to a PR should cancel in-progress runs for the same PR. Defaults to true
  branches:
    include: [ dev, master ] # branch names which will trigger a build

name: $(Year:yyyy).$(Month).$(DayOfMonth)$(Rev:.r)

jobs:
- template: azure-pipeline.template.yaml
  parameters:
    name: "net_tests_windows"
    displayName: ".NET Core Unit Tests (Windows)"
    vmImage: "windows-2019"
    scriptFileName: build.cmd
    scriptArgs: RunTests
    outputDirectory: "TestResults"
    artifactName: "net_tests_windows-$(Build.BuildId)"
- template: azure-pipeline.template.yaml
  parameters:
    name: "net_6_tests_windows"
    displayName: ".NET 6 Unit Tests (Windows)"
    vmImage: "windows-2019"
    scriptFileName: build.cmd
    scriptArgs: RunTestsNet
    outputDirectory: "TestResults"
    artifactName: "net_6_tests_windows-$(Build.BuildId)"
